package com.jetpackdatastore

object DummyString {
    val text =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Libero enim sed faucibus turpis in eu. Tortor consequat id porta nibh. Nisi est sit amet facilisis magna etiam tempor orci eu. Felis eget nunc lobortis mattis. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Lobortis feugiat vivamus at augue eget. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Posuere ac ut consequat semper viverra nam libero justo laoreet. Tristique senectus et netus et malesuada fames ac. Elit duis tristique sollicitudin nibh sit amet commodo.\n" +
            "\n" +
            "Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Id cursus metus aliquam eleifend. Donec ultrices tincidunt arcu non sodales neque sodales ut. Fermentum dui faucibus in ornare quam. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Morbi tincidunt ornare massa eget egestas purus. Nibh mauris cursus mattis molestie a. Accumsan tortor posuere ac ut consequat semper viverra nam. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Consequat semper viverra nam libero justo laoreet sit amet cursus. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Tristique nulla aliquet enim tortor at. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n" +
            "\n" +
            "Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Congue quisque egestas diam in arcu cursus euismod. Pharetra sit amet aliquam id. Lorem sed risus ultricies tristique. Urna neque viverra justo nec ultrices. Diam maecenas sed enim ut. Elementum nisi quis eleifend quam adipiscing. Et egestas quis ipsum suspendisse ultrices gravida. Malesuada fames ac turpis egestas integer eget aliquet nibh. Nisi porta lorem mollis aliquam ut porttitor leo. Ornare arcu dui vivamus arcu. Lobortis scelerisque fermentum dui faucibus in ornare quam. Est ultricies integer quis auctor. A condimentum vitae sapien pellentesque. Dignissim cras tincidunt lobortis feugiat vivamus at augue.\n" +
            "\n" +
            "Eget egestas purus viverra accumsan. Vel quam elementum pulvinar etiam. Augue lacus viverra vitae congue eu consequat ac. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Justo eget magna fermentum iaculis eu non diam phasellus. Ultrices tincidunt arcu non sodales neque. Id leo in vitae turpis massa. Amet massa vitae tortor condimentum lacinia quis. Massa enim nec dui nunc mattis enim ut. Mi quis hendrerit dolor magna eget est lorem. Nascetur ridiculus mus mauris vitae ultricies leo. Commodo odio aenean sed adipiscing diam donec adipiscing. Enim tortor at auctor urna nunc id. Amet massa vitae tortor condimentum. At augue eget arcu dictum varius duis. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sed elementum tempus egestas sed sed risus pretium.\n" +
            "\n" +
            "Amet risus nullam eget felis. At quis risus sed vulputate odio ut enim blandit. Nunc id cursus metus aliquam eleifend. Neque volutpat ac tincidunt vitae semper quis lectus nulla. Bibendum neque egestas congue quisque egestas diam in arcu cursus. Dictum varius duis at consectetur. Ornare aenean euismod elementum nisi quis. Mattis aliquam faucibus purus in massa tempor nec feugiat. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Duis ultricies lacus sed turpis. In cursus turpis massa tincidunt dui ut ornare lectus sit. Massa ultricies mi quis hendrerit dolor. Vestibulum lectus mauris ultrices eros. Suspendisse potenti nullam ac tortor vitae purus faucibus. Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. Turpis massa tincidunt dui ut ornare lectus sit.\n" +
            "\n" +
            "Sit amet aliquam id diam maecenas. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. Ac placerat vestibulum lectus mauris ultrices eros in cursus turpis. Dolor sit amet consectetur adipiscing elit. Fusce ut placerat orci nulla pellentesque dignissim enim. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Nibh ipsum consequat nisl vel pretium lectus. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Commodo nulla facilisi nullam vehicula ipsum a arcu. Est ante in nibh mauris cursus mattis molestie a iaculis. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Et tortor at risus viverra adipiscing at in tellus integer. Condimentum mattis pellentesque id nibh tortor. Sit amet dictum sit amet justo donec enim diam. Magnis dis parturient montes nascetur ridiculus. At auctor urna nunc id cursus metus aliquam eleifend mi. Lacinia at quis risus sed vulputate odio ut enim blandit. Nec tincidunt praesent semper feugiat nibh. A iaculis at erat pellentesque adipiscing commodo. In hac habitasse platea dictumst.\n" +
            "\n" +
            "Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Purus in massa tempor nec feugiat nisl pretium fusce. Sit amet aliquam id diam maecenas ultricies mi eget. Mauris rhoncus aenean vel elit scelerisque. Ut tortor pretium viverra suspendisse potenti nullam. Quam vulputate dignissim suspendisse in est ante. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Maecenas volutpat blandit aliquam etiam erat velit. Cursus vitae congue mauris rhoncus aenean vel. Non curabitur gravida arcu ac. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Nec feugiat nisl pretium fusce id velit ut. Scelerisque purus semper eget duis at tellus. Ante in nibh mauris cursus mattis molestie a. Odio tempor orci dapibus ultrices in iaculis. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Vitae congue eu consequat ac felis donec et odio. Elementum eu facilisis sed odio morbi quis commodo. Nec dui nunc mattis enim ut tellus elementum. Sit amet commodo nulla facilisi nullam vehicula ipsum.\n" +
            "\n" +
            "Varius quam quisque id diam vel quam elementum. Egestas dui id ornare arcu odio. Bibendum enim facilisis gravida neque convallis a cras semper. Est ultricies integer quis auctor elit sed. Tincidunt tortor aliquam nulla facilisi. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Lacus vestibulum sed arcu non odio. Vestibulum sed arcu non odio. Amet consectetur adipiscing elit pellentesque habitant morbi. Suscipit adipiscing bibendum est ultricies integer quis auctor. Libero enim sed faucibus turpis in eu mi. Id consectetur purus ut faucibus pulvinar. Ac felis donec et odio pellentesque diam volutpat commodo sed.\n" +
            "\n" +
            "Lacus suspendisse faucibus interdum posuere lorem ipsum. Fermentum leo vel orci porta non pulvinar. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Accumsan tortor posuere ac ut consequat semper viverra nam. Proin sed libero enim sed. Eget nunc scelerisque viverra mauris in aliquam sem. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Arcu vitae elementum curabitur vitae nunc. Ac tortor vitae purus faucibus ornare suspendisse. Quisque id diam vel quam elementum pulvinar. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Ornare aenean euismod elementum nisi quis eleifend. Orci sagittis eu volutpat odio facilisis mauris sit amet. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Nisi lacus sed viverra tellus in hac habitasse platea dictumst."

    val longText =
        text + text + text + text + text + text + text + text + text + text + text + text + text + text +
            text + text + text + text + text + text + text + text + text + text + text + text + text + text +
            text + text + text + text + text + text + text + text + text + text + text + text + text + text +
            text + text + text + text + text + text + text + text + text + text + text + text + text + text
}